### ISSUE TITLE
update library to be compatible with latest react table library 

### ISSUE THREAD

**Issue by anishpatelyaadada** [GuillaumeJasmin/react-table-sticky#1]
the app is not working with the latest version of react table

**Comment by GuillaumeJasmin** [comment]
Please, provide more information than "it's not working".
What doesn't work ?
The code sandbox demo is up to date with the latest version `7.0.0-rc.15` and it seems to work https://codesandbox.io/s/sweet-cori-gl81g

**Comment by anishpatelyaadada** [comment]
@GuillaumeJasmin thank you so much for your comment. The stick right column works but not the left one

**Comment by anishpatelyaadada** [comment]
@GuillaumeJasmin Any update

**Comment by GuillaumeJasmin** [comment]
Any update on what ? codesandbox example works for me.
Please provide a screenshot and code example of your bug, and if you find the answer too slow, you can open a PR and make changes by yourself

**Comment by anishpatelyaadada** [comment]
Thank you
