### ISSUE TITLE
iOS sticky columns headers are jumpy

### ISSUE THREAD

**Issue by bogdancss** [GuillaumeJasmin/react-table-sticky#11]
I noticed that the headers of the sticky columns are jumpy when side-scrolling on iOS devices.
Here's a [recording](https://streamable.com/b8x6b1) of a slightly modified demo (just removed some of the table structure from the demo).

You can see that only the headers present this behaviour and not the entire sticky column.

**Comment by GuillaumeJasmin** [comment]
I @bogdancss 
Thanks for your feedback.
As react-table-sticky fully use sticky css property, I think it's not an issue with this lib, but with the implementation of sticky on iOS.
There is no hack like calculating position on the fly on each scroll event, so I don't really know how to fix that.

Could you give me the link of codesandbox please ?

**Comment by bogdancss** [comment]
Hey @GuillaumeJasmin  - yes, it seems to just be how ios handles position sticky within another sticky positioned parent.
If you load the demo on the repo readme, you can actually see this happening.

**Comment by bogdancss** [comment]
We ended up just leaving this as is - there is nothing wrong with the lib, so I can close off this issue.
