### ISSUE TITLE
Sticky Columns are not working on Safari

### ISSUE THREAD

**Issue by luis-carlos-campos** [GuillaumeJasmin/react-table-sticky#3]
Hi everyone,

Sticky Columns do not seem to work on Safari.

Safari: Version 12.0 (14606.1.36.1.9)

**Comment by GuillaumeJasmin** [comment]
codesandbox demo works for me on Safari Version 13.0.
I haven't any Safari 12.0 to test it now

**Comment by luis-carlos-campos** [comment]
It does look good on 13+

I'll try to test it on others Safari versions

Safari 12:

![Screen-Recording-2020-03-16-at-2 37 28-PM](https://user-images.githubusercontent.com/13797951/76785474-480f3b80-6794-11ea-9b69-486dcf58b409.gif)

**Comment by GuillaumeJasmin** [comment]
@luis-carlos-campos thanks, so sticky position works for scroll Y but not scroll X.
I will investigate

**Comment by luis-carlos-campos** [comment]
@GuillaumeJasmin Great, Thanks! I appreciate your time.

**Comment by GuillaumeJasmin** [comment]
I found the issue, it's about css prefix. It require `position: -webkit-sticky;` but it require some internal changes because sticky position is currently set with inline style

**Comment by GuillaumeJasmin** [comment]
fixed on `v1.1.0` . See [release note](https://github.com/GuillaumeJasmin/react-table-sticky/releases/tag/v1.1.0) for upgrade

**Comment by luis-carlos-campos** [comment]
Awesome. Thanks!
