### ISSUE TITLE
Sticky did not work well

### ISSUE THREAD

**Issue by jtamm-red** [GuillaumeJasmin/react-table-sticky#6]
TypeError
Cannot read property 'sticky' of undefined

https://codesandbox.io/s/react-table-sticky-official-jivux

**Comment by GuillaumeJasmin** [comment]
Hi @jtamm-red 
Please, take a little time to explain what you do with react-table and your data, before juste say "TypeError" like a simple error logger.

So, I take time to understand what you try to do with your data, and you simply use an undefined column `firstElement` . So sticky work well, your columns props is just invalid.
