### ISSUE TITLE
Open PR for core library?

### ISSUE THREAD

**Issue by roginfarrer** [GuillaumeJasmin/react-table-sticky#8]
Hi there! Thanks for this library! It's awesome to expand on features of a large libraries.

I'm wondering if you've considered opening a PR to add this feature to the react-table library itself. I don't know what Tanner thinks of the feature, but IMO this seems like a natural addition.

And selfishly, I maintain a component library that will encourage its use with react-table, and it would be nice to point users to react-table only, instead of having to seek out other plugins!

**Comment by GuillaumeJasmin** [comment]
Hi @roginfarrer 
Thanks for this idea. I already think about that, but react-table v7 is headless, and it's the main purpose of v7 compare to v6.
`react-table-sticky` is just an UI add on, and I don't think Tanner want include UI into v7.
But if this project can be include into react-table, it could be a good thing

@tannerlinsley what do you think ?

**Comment by tannerlinsley** [comment]
v7 doesn't really house any table markup, which sticky-headers definitely need. So even if we wanted to add it to the core library, there isn't really anywhere it could go. Also, sticky headers are still a very opinionated thing on how they are implemented. I think it's best to keep this out of the core for now.

**Comment by roginfarrer** [comment]
Thank you both for considering!
